baseURL = "/"
title = "XXII Cenáculo NcOrLx"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
googleAnalytics = "G-G847G6KWGL"

[params]
fancyTitle = '<img srcset="/img/logo.png 484w, /img/logo_sm.png 242w" sizes="(max-width: 600px) 242px, 484px"> <br/> XXII Cenáculo NcOrLx'  # title for frontpage, may include image
copyright = "XXII Cenáculo NcOrLx"
source = "https://github.com/CanIBeFii/cenaculo_NcOrLx_site"
author = "CanIBeFii"
authorurl = "https://github.com/CanIBeFii"
description = '1, 2 e 3 de março de 2024. Estás preparado?!' # description below title on frontpage
startbuttonText = "Inscrições"  # text on the start button
startbuttonLink = "https://forms.gle/7cLAoP8kf2qHVwvX6"
body_is_markdown = true
# custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Página Inicial"

[[params.menu.main]]
url = 'informacoes-adicionais/merch'
title = "Merch Cenaculo"

[[params.menu.main]]
url = '/equipa-projeto/'
title = "Equipa Projeto"

[[params.menu.main]]
url = 'informacoes-adicionais/atividades'
title = "Reportório de Oportunidades"

[[params.menu.main]]
url = "https://cenaculo.netlify.app/"
title = "Ciclos Passados"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"


[params.one]
enable = true
title = 'Olá Caminheiros!'
href = "/equipa-projeto/"
text = "clica aqui!"
body = '''
Bem-vindos ao XXII Ciclo de Cenáculo do Núcleo Oriental de Lisboa! O Cenáculo existe com o intuito de nos ajudar a desenvolver o nosso poder para fazermos parte da mudança e construirmos juntos, a realidade que desejamos. No XXII Ciclo esperamos que acreditem neste vosso poder e venham fazer este caminho de descoberta e aprendizagem connosco.

Sempre que precisem a EP está cá para vos apoiar, somos caminheiros como vocês portanto não hesitem em falar com qualquer um de nós!

"Para fazer algo especial só precisas de acreditar que é especial." **Acredita**, **Partilha Y Avança**!

Canhotas AmYgas,\
Equipa Projeto do XXII Ciclo de Cenáculo do Núcleo Oriental
'''

special = false


[params.two]
enable = true

[[params.two.section]]
img = "img/angariacoes.jpg"
title = 'ANGARIAÇÕES DE FUNDOS'
body = 'Não vão faltar momentos de partilha entre o núcleo!'
button = true

[[params.two.section.link]]
href = "angariacoes-fundo/juntarada"
text = "JUNTARADA"

[[params.two.section.link]]
href = "angariacoes-fundo/cinema"
text = "CINEMA"

[[params.two.section.link]]
href = "angariacoes-fundo/cafe-concerto"
text = "CAFÉ CONCERTO"

[[params.two.section]]
img = "img/encontro-local.jpg"
title = 'ENCONTRO LOCAL'
body = 'Todos os caminhos vão dar ao Encontro Local :)'
button = true

[[params.two.section.link]]
href = "https://forms.gle/7cLAoP8kf2qHVwvX6"
text = "INSCRIÇÃO"

[[params.two.section.link]]
href = "encontro-local/informacoes"
text = "INFORMAÇÕES"

[[params.two.section]]
img = "img/equipa-projeto.jpg"
title = 'EQUIPA PROJETO'
body = 'Conhece um pouco sobre cada membro da EP!'
button = true

[[params.two.section.link]]
href = "equipa-projeto"
text = "EQUIPA PROJETO"

[[params.two.section]]
img = "img/carta-cenaculo.jpg"
title = 'CARTA DE CENÁCULO'
body = '''Aqui podes aceder à carta de Cenáculo.

No reportório podes encontrar diversas atividades para caminheiros, a nível nacional ou regional.'''
button = true

[[params.two.section.link]]
href = "forum/carta-cenaculo"
text = "CARTA DE CENÁCULO"

[[params.two.section.link]]
href = "informacoes-adicionais/atividades"
text = "REPORTÓRIO DE OPORTUNIDADES"

[params.contact]
enable = true
title = "Contacta-nos"
body = "Ficaste com alguma dúvida? Envia-nos uma mensagem!"
email = "cenaculo.oriental@escutismo.pt"
subject = "Nova mensagem!"
formspree_form_id = "xqkjlryg"

[params.social]
twitter = ""
facebook = "cenac.ncorlx"
instagram = "cenaculo.ncorlx"
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
